name: "DSLstats"
description: "Monitor DSL stats"
version: "0.1.2"
slug: "dslstats"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5900/tcp: 5900
  55555/tcp: 55555
host_network: true
map: 
  - config:rw
  - share:rw
